import { useState } from "react";
import "../Services.scss";
import CreateCaptionFromIdea from "./CreateCaptionFromIdea";

const fakeListIdeaGeneratedAl = [
  {
    title: "Idea generated by AI 1",
    data: {},
  },
  {
    title: "Idea generated by AI 2",
    data: {},
  },
  {
    title: "Idea generated by AI 3",
    data: {},
  },
  {
    title: "Idea generated by AI 4",
    data: {},
  },
  {
    title: "Idea generated by AI 5",
    data: {},
  },
  {
    title: "Idea generated by AI 6",
    data: {},
  },
  {
    title: "Idea generated by AI 7",
    data: {},
  },
];

interface IdeaGeneratedItem {
  title: string;
  data: Record<string, unknown>;
}

const GetInspried = () => {
  const [topic, setTopic] = useState("");
  const [chooseIdeaGeneratedFromAI, setChooseIdeaGeneratedFromAI] = useState(false);
  const [listIdeaGenerated, setListIdeaGenerated] =
    useState<IdeaGeneratedItem[]>();
  const [ideaToBuildPosts, setIdeaToBuildPosts] = useState<string>();

  if (ideaToBuildPosts)
    return <CreateCaptionFromIdea ideaGeneratedFromAI={ideaToBuildPosts} />;

  const renderTypingTopic = () => (
    <div className="TypingTopic">
      <div className="SuggestInspried">
        Stick staring at a blank page? Tell us what topic you have in mind and
        Skipli AI will generate a list of post ides and captions for you.
      </div>
      <div className="InputTopicInspried">
        <div className="TitleInput">What topic do you want ideas for?</div>
        <input
          type="text"
          className="InputTopic"
          placeholder="Enter a topic"
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
        />
      </div>
      <div className="RowButtonGenerateCaption">
        <button
          className="ButtonGenerateCaption"
          onClick={() => {
            //TODO: fake API list idea
            setListIdeaGenerated(fakeListIdeaGeneratedAl);
            setChooseIdeaGeneratedFromAI(true);
          }}
        >
          Generate ideas
        </button>
      </div>
    </div>
  );

  const renderListIdeaGenerated = () => (
    <div className="ListIdeaGenerated">
      <div className="SuggestIdeaGenerated">
        Choose an idea to build some posts
      </div>
      {listIdeaGenerated &&
        listIdeaGenerated.length > 0 &&
        listIdeaGenerated.map((el, idx) => (
          <div
            key={`${el.title}${idx}`}
            className="IdeaGeneratedItem"
            onClick={() => setIdeaToBuildPosts(el.title)}
          >
            {el.title}
          </div>
        ))}
    </div>
  );

  return (
    <div className="GetInspried">
      <div className="GetInspriedContainer">
        <h2>Get Inspried</h2>
        {chooseIdeaGeneratedFromAI ? renderListIdeaGenerated() : renderTypingTopic()}
      </div>
    </div>
  );
};

export default GetInspried;
