import ContentItem from "../../components/ContentItem/ContentItem";
import "./Profile.scss";

const BlockContent = [
  {
    headerTitle: "Skipli is launching SkipliAI",
    listChidContent: [
      {
        title: "Skipli AI - the smarter",
        content:
          "Introducing Skipli AI - the smarter, faster way to craft compelling content  Experience all the magic of Al-driven wriing assistant and get great results with fewer headaches.#AI #ContentMarketing #Content",
      },
      {
        title: "SkipliAl creating content Social Media",
        content:
          "Say goodbye to writer's block  #SkipliAl is now available to make creating attention-grabbing content easie thaneverGeready totake yoursocialmedia game to the next level with #AI#SocialMedia #Writing",
      },
    ],
  },
  {
    headerTitle: "Idea generated by AI 2",
    listChidContent: [
      {
        title: "Skipli AI - the smarter",
        content:
          "Introducing Skipli AI - the smarter, faster way to craft compelling content  Experience all the magic of Al-driven wriing assistant and get great results with fewer headaches.#AI #ContentMarketing #Content",
      },
      {
        title: "SkipliAl creating content Social Media",
        content:
          "Say goodbye to writer's block  #SkipliAl is now available to make creating attention-grabbing content easie thaneverGeready totake yoursocialmedia game to the next level with #AI#SocialMedia #Writing",
      },
    ],
  },
];

const Profile = () => {
  const handleShare = (data: any) => {
    console.log("Share", data);
  };

  const handleUnSave = (data: any) => {
    console.log("UnSave", data);
  };

  return (
    <div className="Profile">
      <h2>Saved Content</h2>
      <div className="SaveContentContainer">
        {BlockContent.map((el) => (
          <div key={el.headerTitle} className="BlockContent">
            <div className="HeaderTitle">{el.headerTitle}</div>
            <div className="ListContentContainer">
              {el.listChidContent.length > 0 &&
                el.listChidContent.map((item, idx) => (
                  <ContentItem
                    key={`${item.title}${idx}`}
                    className={"ContentItemGrid"}
                    content={item.content}
                    title={item.title}
                    onShare={() => handleShare(item)}
                    onUnsave={() => handleUnSave(item)}
                  />
                ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Profile;
